//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::Point;
use sea_orm::{entity::prelude::*, FromJsonQueryResult};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, FromJsonQueryResult)]
#[serde(transparent)]
pub struct ListPoints(pub Vec<Point>);

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wms_paths")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub tenant_id: i64,
    pub zone_id: i64,
    pub from_node_id: i64,
    pub to_node_id: i64,
    pub name: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub is_one_way: bool,
    pub status: i32,

    #[sea_orm(column_type = "JsonBinary")]
    pub sharp: Option<ListPoints>,

    #[sea_orm(column_type = "Double")]
    pub distance: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
