//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::{entity::prelude::*, FromJsonQueryResult};
use serde::{Deserialize, Serialize};

use super::Point;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, FromJsonQueryResult)]
#[serde(transparent)]
pub struct ListPoints(pub Vec<Point>);

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wms_picking_routes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,

    pub tenant_id: i32,
    pub depend_id: Option<i32>,
    pub picking_id: Option<i32>,
    pub status: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub paths: Option<ListPoints>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
