//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wms_zones")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub tenant_id: i64,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub name: String,
    pub description: String,

    #[sea_orm(column_type = "Double")]
    pub pos_x: f64,

    #[sea_orm(column_type = "Double")]
    pub pos_y: f64,

    #[sea_orm(column_type = "Double")]
    pub height: f64,

    #[sea_orm(column_type = "Double")]
    pub width: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
