[package]
name = "frontend"
version = "1.0.1"
edition = "2021"

[dependencies]
leptos = { version = "0.6", features = ["csr"] } # Client-side rendering
leptos_router = { version = "0.6", features = ["csr"] }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
