version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algorithm
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    volumes:
      - ./secrets:/app/secrets
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.ip_local_port_range=1024 65535
    environment:
      - APP_ENV=dev
      - SOPS_AGE_KEY_CONTENT=${SOPS_AGE_KEY_CONTENT}
    depends_on:
      - db
      - valkey
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: default
      MYSQL_USER: admin
      MYSQL_PASSWORD: rootroot
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  valkey:
    image: valkey/valkey:9.0-alpine
    command: valkey-server --requirepass rootroot
    container_name: valkey-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
