
map $uri $jwt_required {
    ~^/api/debug/                       0;
    ~^/api/investing/v1/ohcl/           0;
    ~^/api/investing/v2/                0;
    ~^/api/chat/v1/facebook/webhook     0;
    ~^/api/chat/v1/slack/webhook        0;
    ~^/api/ecommerce/v1/wms/shelves     1;
    default                             2;
}
