
map $host $doc_type {
    default                     0;
    localhost                   1;
    lighttrading.pp.ua          1;
    docs.lighttrading.pp.ua     1;
}

map $host $doc_location {
    localhost                admin;
    lighttrading.pp.ua       investing;
    docs.lighttrading.pp.ua  investing;
    default                  "";
}
