map "$http_cf_ray:$request_uri" $is_attack {
    default                     "1";      # Mặc định là nghi vấn
    "~^.+:.+"                   "";       # Có CF-Ray (bất kể URI nào) -> OK
    "~^:/debug/pprof/profile"   "";       # Không có CF-Ray nhưng là /health -> OK
    "~^:/health"                "";       # Không có CF-Ray nhưng là /health -> OK
    "~^:/metrics"               "";       # Không có CF-Ray nhưng là /health -> OK
}
