#!/bin/sh
set -e

systemctl daemon-reload

echo "Doing '$1'"
if [ "$1" = "configure" ]; then
    systemctl enable bff
    systemctl start bff
elif [ "$1" = "upgrade" ]; then
    echo "Not changing configuration. This is an upgrade."
    systemctl stop bff
    systemctl start bff
fi

echo "Done executing post install scripts."
