-- =========================================================================
-- DANH SÁCH CÁC BẢNG LIÊN QUAN INVENTORY
-- =========================================================================
CREATE TABLE IF NOT EXISTS wms_stocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  unit VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_wms_stocks_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS wms_contents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  stock_id BIGINT NOT NULL,
  uname VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_wms_contents_tenant_stock UNIQUE (tenant_id, stock_id)
);

CREATE TABLE IF NOT EXISTS wms_lots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  lot_number VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  supplier VARCHAR(255),
  entry_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cost_price DOUBLE PRECISION,
  status INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_wms_lots_tenant_lot_number UNIQUE (tenant_id, lot_number)
);

CREATE TABLE IF NOT EXISTS wms_stock_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  stock_id BIGINT NOT NULL,
  lot_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  status INTEGER NOT NULL,
  expired_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_wms_stock_entries_tenant_stock_lot UNIQUE (tenant_id, stock_id, lot_id)
);

CREATE TABLE IF NOT EXISTS wms_shelves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  publish BOOLEAN DEFAULT FALSE,
  description VARCHAR(255),
  node INTEGER DEFAULT 0,
  zone INTEGER DEFAULT 0,
  is_left BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_wms_shelves_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS wms_stock_shelves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  stock_id BIGINT NOT NULL,
  shelf_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_wms_stock_shelves_tenant_stock_shelf UNIQUE (tenant_id, stock_id, shelf_id)
);

-- Bảng Partition mẫu: wms_sales
CREATE TABLE IF NOT EXISTS wms_sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  cost_price DOUBLE PRECISION NOT NULL,
  status INTEGER DEFAULT 0,
  version INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, created_at), -- Bắt buộc phải có created_at trong PK để phân vùng
  CONSTRAINT unique_wms_sales_tenant_order UNIQUE (tenant_id, order_id, created_at)
) PARTITION BY RANGE (created_at);

-- Bảng Partition mẫu: wms_sale_events
CREATE TABLE IF NOT EXISTS wms_sale_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  sale_id BIGINT NOT NULL,
  stock_id BIGINT NOT NULL,
  count INTEGER NOT NULL,
  version INTEGER DEFAULT 0,
  status INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, created_at),
  CONSTRAINT unique_wms_sale_events_tenant_sale_id UNIQUE (tenant_id, sale_id, stock_id, version, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE IF NOT EXISTS wms_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  stock_id BIGINT NOT NULL,
  lot_id BIGINT NOT NULL,
  shelf_id BIGINT,
  order_id BIGINT,
  assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expired_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status INTEGER DEFAULT 0,
  cost_price DOUBLE PRECISION NOT NULL,
  barcode VARCHAR(255)
);


-- =========================================================================
-- DANH SÁCH CÁC BẢNG LIÊN QUAN TOPOLOGY
-- =========================================================================

CREATE TABLE IF NOT EXISTS wms_zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  pos_x REAL NOT NULL DEFAULT 0, -- Chuyển sang REAL hoặc DOUBLE PRECISION
  pos_y REAL NOT NULL DEFAULT 0,
  height REAL NOT NULL,
  width REAL NOT NULL,
  CONSTRAINT unique_wms_zones_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS wms_nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  zone_id BIGINT,
  name VARCHAR(255),
  kind INTEGER NOT NULL DEFAULT 0,
  pos_x REAL NOT NULL DEFAULT 0,
  pos_y REAL NOT NULL DEFAULT 0,
  CONSTRAINT unique_wms_nodes_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS wms_paths (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  from_node_id BIGINT,
  to_node_id BIGINT,
  name VARCHAR(50),
  zone_id BIGINT,
  distance REAL,
  is_one_way BOOLEAN DEFAULT FALSE,
  sharps JSONB, -- Sử dụng JSONB tối ưu hiệu năng xử lý hình học/tọa độ phẳng
  status INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT unique_wms_paths_tenant_name UNIQUE (tenant_id, name)
);


-- =========================================================================
-- DANH SÁCH CÁC BẢNG LIÊN QUAN FEATURE PICKING (CÁC BẢNG ĐỀU PHÂN VÙNG)
-- =========================================================================

-- Bảng Partition mẫu: wms_picking_plans
CREATE TABLE IF NOT EXISTS wms_picking_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  version INTEGER DEFAULT 0,
  status INTEGER,
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE IF NOT EXISTS wms_picking_plans_in_zones (
  id BIGINT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wms_picking_plans_in_nodes (
  id BIGINT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bảng Partition mẫu: wms_picking_routes
CREATE TABLE IF NOT EXISTS wms_picking_routes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  tenant_id BIGINT NOT NULL,
  depend_id BIGINT,
  picking_id BIGINT,
  status INTEGER,
  version INTEGER DEFAULT 0,
  paths JSONB,
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- Bảng Partition mẫu: wms_picking_goods
CREATE TABLE IF NOT EXISTS wms_picking_goods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  sale_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  route_id BIGINT,
  event_id BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status INTEGER,
  is_ready_to_pack BOOLEAN,
  PRIMARY KEY (id, created_at),
  CONSTRAINT unique_wms_picking_goods_tenant_sale UNIQUE (tenant_id, sale_id, created_at)
) PARTITION BY RANGE (created_at);

-- Bảng Partition mẫu: wms_picking_plan_events
CREATE TABLE IF NOT EXISTS wms_picking_plan_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  version INTEGER NOT NULL,
  status INTEGER NOT NULL,
  PRIMARY KEY (id, created_at),
  CONSTRAINT unique_wms_picking_plan_events_tenant_plan_status UNIQUE (tenant_id, plan_id, version, created_at)
) PARTITION BY RANGE (created_at);

-- Bảng Partition mẫu: wms_picking_route_events
CREATE TABLE IF NOT EXISTS wms_picking_route_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  version INTEGER NOT NULL,
  actor_id BIGINT NOT NULL,
  route_id BIGINT NOT NULL,
  status INTEGER NOT NULL,
  PRIMARY KEY (id, created_at),
  CONSTRAINT unique_wms_picking_route_events_tenant_route_status UNIQUE (tenant_id, route_id, version, created_at)
) PARTITION BY RANGE (created_at);

-- Bảng Partition mẫu: wms_picking_items
CREATE TABLE IF NOT EXISTS wms_picking_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  item_id BIGINT,
  event_id BIGINT,
  route_id BIGINT,
  ledger_id BIGINT,
  barcode VARCHAR(255),
  PRIMARY KEY (id, created_at),
  CONSTRAINT unique_wms_picking_items_tenant_item_event UNIQUE (tenant_id, item_id, created_at)
) PARTITION BY RANGE (created_at);


-- =========================================================================
-- GẮN TRIGGER CHO CÁC BẢNG KHÔNG PHÂN VÙNG (CHỈ CẬP NHẬT TIME)
-- =========================================================================

CREATE TRIGGER trg_wms_stocks_updated_at BEFORE UPDATE ON wms_stocks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wms_contents_updated_at BEFORE UPDATE ON wms_contents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wms_lots_updated_at BEFORE UPDATE ON wms_lots FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wms_stock_entries_updated_at BEFORE UPDATE ON wms_stock_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wms_shelves_updated_at BEFORE UPDATE ON wms_shelves FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wms_stock_shelves_updated_at BEFORE UPDATE ON wms_stock_shelves FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wms_items_updated_at BEFORE UPDATE ON wms_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wms_zones_updated_at BEFORE UPDATE ON wms_zones FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wms_nodes_updated_at BEFORE UPDATE ON wms_nodes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wms_paths_updated_at BEFORE UPDATE ON wms_paths FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wms_picking_plans_in_zones_updated_at BEFORE UPDATE ON wms_picking_plans_in_zones FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wms_picking_plans_in_nodes_updated_at BEFORE UPDATE ON wms_picking_plans_in_nodes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- =========================================================================
-- GẮN TRIGGER TỰ ĐỘNG SINH PHÂN VÙNG KHI INSERT DỮ LIỆU
-- =========================================================================

CREATE TRIGGER trg_wms_sales_partition BEFORE INSERT ON wms_sales FOR EACH ROW EXECUTE FUNCTION auto_create_monthly_partition();
CREATE TRIGGER trg_wms_sale_events_partition BEFORE INSERT ON wms_sale_events FOR EACH ROW EXECUTE FUNCTION auto_create_monthly_partition();
CREATE TRIGGER trg_wms_picking_plans_partition BEFORE INSERT ON wms_picking_plans FOR EACH ROW EXECUTE FUNCTION auto_create_monthly_partition();
CREATE TRIGGER trg_wms_picking_routes_partition BEFORE INSERT ON wms_picking_routes FOR EACH ROW EXECUTE FUNCTION auto_create_monthly_partition();
CREATE TRIGGER trg_wms_picking_goods_partition BEFORE INSERT ON wms_picking_goods FOR EACH ROW EXECUTE FUNCTION auto_create_monthly_partition();
CREATE TRIGGER trg_wms_picking_plan_events_partition BEFORE INSERT ON wms_picking_plan_events FOR EACH ROW EXECUTE FUNCTION auto_create_monthly_partition();
CREATE TRIGGER trg_wms_picking_route_events_partition BEFORE INSERT ON wms_picking_route_events FOR EACH ROW EXECUTE FUNCTION auto_create_monthly_partition();
CREATE TRIGGER trg_wms_picking_items_partition BEFORE INSERT ON wms_picking_items FOR EACH ROW EXECUTE FUNCTION auto_create_monthly_partition();
