-- =========================================================================
-- ĐỊNH NGHĨA HỆ THỐNG CÁC BẢNG DỮ LIỆU TÀI CHÍNH (OHCL)
-- =========================================================================

CREATE TABLE IF NOT EXISTS ohcl_brokers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(100) NOT NULL,
  alias INTEGER DEFAULT NULL,
  CONSTRAINT unique_ohcl_brokers_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS ohcl_products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broker_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(500) NOT NULL,
  enabled BOOLEAN DEFAULT FALSE,
  CONSTRAINT unique_ohcl_products_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS ohcl_resolution (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  resolution VARCHAR(5) NOT NULL,
  CONSTRAINT unique_ohcl_resolution_val UNIQUE (resolution)
);

CREATE TABLE IF NOT EXISTS ohcl_mapping_broker_resolution (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broker_id INTEGER,
  resolution_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  resolution VARCHAR(5) NOT NULL,
  CONSTRAINT unique_broker_resolution UNIQUE (broker_id, resolution_id)
);

CREATE TABLE IF NOT EXISTS ohcl_broker_limitation (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broker_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  guest_max_history_days INTEGER DEFAULT 7,
  guest_invisible BOOLEAN DEFAULT FALSE,
  CONSTRAINT unique_broker_limitation UNIQUE (broker_id)
);

CREATE TABLE IF NOT EXISTS ohcl_symbols (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broker_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  name VARCHAR(255) NOT NULL,
  symbol VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_symbol_per_broker UNIQUE (broker_id, product_id, symbol)
);

CREATE TABLE IF NOT EXISTS ohcl_stores (
  id INTEGER PRIMARY KEY, -- Giữ nguyên kiểu gán ID tường minh từ cấu hình map của bạn
  name VARCHAR(500) NOT NULL,
  website VARCHAR(200),
  phone VARCHAR(40),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_ohcl_stores_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS ohcl_store_locations (
  id INTEGER PRIMARY KEY,
  store INTEGER NOT NULL,
  address_line VARCHAR(500),
  district VARCHAR(100),
  province VARCHAR(100),
  latitude REAL NOT NULL DEFAULT 0,
  longitude REAL NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_store_address UNIQUE (address_line, district, province)
);

CREATE TABLE IF NOT EXISTS ohcl_mapping_product_in_store_to_symbol (
  id INTEGER PRIMARY KEY,
  symbol INTEGER,
  store INTEGER NOT NULL,
  product_name VARCHAR(500) NOT NULL,
  alias VARCHAR(500),
  scope INTEGER NOT NULL DEFAULT 0,
  location INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ohcl_price_current (
  id INTEGER PRIMARY KEY, -- Khóa chính map 1-1 thẳng sang bảng ohcl_mapping_product_in_store_to_symbol.id
  buy DOUBLE PRECISION NOT NULL DEFAULT 0,
  sell DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Chuyển đổi sang bảng Partition thực tế để gánh tải lượng ghi dữ liệu lịch sử real-time lớn
CREATE TABLE IF NOT EXISTS ohcl_price_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  symbol_id INTEGER NOT NULL, -- Map trực tiếp tới id của ohcl_mapping_product_in_store_to_symbol
  buy DOUBLE PRECISION NOT NULL DEFAULT 0,
  sell DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, created_at) -- Bắt buộc trong Postgres để thực hiện phân vùng theo time-range
) PARTITION BY RANGE (created_at);

CREATE TABLE IF NOT EXISTS ohcl_product_anchors (
  id INTEGER PRIMARY KEY, -- Map trực tiếp sang ohcl_mapping_product_in_store_to_symbol.id
  store INTEGER NOT NULL,
  symbol INTEGER NOT NULL,
  scope INTEGER NOT NULL DEFAULT 0,
  description VARCHAR(200),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_store_symbol_anchor UNIQUE (store, symbol)
);

CREATE TABLE IF NOT EXISTS ohcl_bank_interest_rate (
  id INTEGER PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "1_month" REAL,  -- Postgres yêu cầu bọc double-quote cho tên cột bắt đầu bằng số
  "3_month" REAL,
  "6_month" REAL,
  "9_month" REAL,
  "12_month" REAL
);


-- =========================================================================
-- ĐÍNH KÈM TRIGGER THAY ĐỔI DỮ LIỆU & PHÂN VÙNG TỰ ĐỘNG
-- =========================================================================

-- Gắn trigger cập nhật thời gian updated_at cho các bảng thường
CREATE TRIGGER trg_ohcl_brokers_updated_at BEFORE UPDATE ON ohcl_brokers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ohcl_products_updated_at BEFORE UPDATE ON ohcl_products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ohcl_resolution_updated_at BEFORE UPDATE ON ohcl_resolution FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ohcl_mapping_broker_resolution_updated_at BEFORE UPDATE ON ohcl_mapping_broker_resolution FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ohcl_broker_limitation_updated_at BEFORE UPDATE ON ohcl_broker_limitation FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ohcl_symbols_updated_at BEFORE UPDATE ON ohcl_symbols FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ohcl_stores_updated_at BEFORE UPDATE ON ohcl_stores FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ohcl_store_locations_updated_at BEFORE UPDATE ON ohcl_store_locations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ohcl_mapping_product_in_store_to_symbol_updated_at BEFORE UPDATE ON ohcl_mapping_product_in_store_to_symbol FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ohcl_price_current_updated_at BEFORE UPDATE ON ohcl_price_current FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ohcl_product_anchors_updated_at BEFORE UPDATE ON ohcl_product_anchors FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ohcl_bank_interest_rate_updated_at BEFORE UPDATE ON ohcl_bank_interest_rate FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Gắn trigger tự động kiểm tra và sinh phân vùng khi insert dữ liệu lịch sử giá mới
CREATE TRIGGER trg_ohcl_price_history_partition BEFORE INSERT ON ohcl_price_history FOR EACH ROW EXECUTE FUNCTION auto_create_ohcl_history_partition();
