CREATE TABLE IF NOT EXISTS sys_sitemap (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  loc TEXT,
  freq VARCHAR(100),
  priority DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS sys_articlemap (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(512),
  loc TEXT,
  title TEXT,
  language VARCHAR(100),
  keywords TEXT
);

CREATE TABLE IF NOT EXISTS sys_filemap (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  src VARCHAR(2048) NOT NULL,
  dest VARCHAR(2048) NOT NULL
);
-- Tạo index riêng biệt theo chuẩn Postgres thay vì khai báo trong CREATE TABLE
CREATE INDEX IF NOT EXISTS idx_sys_filemap_tenant_id ON sys_filemap (tenant_id);

CREATE TABLE IF NOT EXISTS sys_token_map (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  service VARCHAR(200) NOT NULL,
  token BYTEA NOT NULL, -- Chuyển từ VARBINARY sang BYTEA

  CONSTRAINT uk_tenant_service UNIQUE (tenant_id, service)
);

CREATE TABLE IF NOT EXISTS sys_tenant (
  host VARCHAR(200) PRIMARY KEY,
  id BIGINT NOT NULL UNIQUE,
  jwt_mode VARCHAR(20) DEFAULT NULL,
  jwt_secret BIGINT DEFAULT NULL, -- Trỏ tới sys_token_map.id
  oidc_jwks_url VARCHAR(500) DEFAULT NULL,
  oidc_issuer VARCHAR(255) DEFAULT NULL,
  oidc_client_id VARCHAR(255) DEFAULT NULL, -- Client ID công khai (chuỗi)
  oidc_client_secret BIGINT DEFAULT NULL, -- Trỏ tới sys_token_map.id
  oidc_expected_alg VARCHAR(10) DEFAULT NULL,
  session_secret BIGINT DEFAULT NULL, -- Trỏ tới sys_token_map.id
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
-- Thêm comment tài liệu hóa hệ thống trong Postgres
COMMENT ON COLUMN sys_tenant.jwt_secret IS 'Trỏ tới sys_token_map.id';
COMMENT ON COLUMN sys_tenant.oidc_client_id IS 'Client ID công khai (chuỗi)';
COMMENT ON COLUMN sys_tenant.oidc_client_secret IS 'Trỏ tới sys_token_map.id';
COMMENT ON COLUMN sys_tenant.session_secret IS 'Trỏ tới sys_token_map.id';

CREATE TABLE IF NOT EXISTS sys_api_map (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  mode INTEGER,
  name VARCHAR(200),
  url VARCHAR(1000),
  parser JSONB, -- Chuyển từ JSON sang JSONB để tối ưu hiệu năng query

  CONSTRAINT unique_tenant_name_mode UNIQUE (tenant_id, name, mode)
);

CREATE TABLE IF NOT EXISTS sys_database_map (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  token VARCHAR(200),

  CONSTRAINT unique_tenant UNIQUE (tenant_id)
);

CREATE TABLE IF NOT EXISTS sys_table_map (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  backend INTEGER,
  name VARCHAR(200),
  "schema" JSONB, -- Bọc nháy kép do trùng từ khóa hệ thống và dùng JSONB

  CONSTRAINT unique_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS sys_streams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  context JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_sinks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  handler JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_link_streams_to_sinks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  sink_id BIGINT NOT NULL,
  stream_id BIGINT NOT NULL,
  enabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_sys_sitemap_updated_at BEFORE UPDATE ON sys_sitemap FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sys_articlemap_updated_at BEFORE UPDATE ON sys_articlemap FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sys_filemap_updated_at BEFORE UPDATE ON sys_filemap FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sys_token_map_updated_at BEFORE UPDATE ON sys_token_map FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sys_tenant_updated_at BEFORE UPDATE ON sys_tenant FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sys_api_map_updated_at BEFORE UPDATE ON sys_api_map FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sys_database_map_updated_at BEFORE UPDATE ON sys_database_map FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sys_table_map_updated_at BEFORE UPDATE ON sys_table_map FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sys_streams_updated_at BEFORE UPDATE ON sys_streams FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sys_sinks_updated_at BEFORE UPDATE ON sys_sinks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sys_link_streams_to_sinks_updated_at BEFORE UPDATE ON sys_link_streams_to_sinks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
