-- Chuyển đổi dữ liệu sang PostgreSQL sử dụng ON CONFLICT để thay thế INSERT IGNORE
INSERT INTO sys_api_map (id, tenant_id, mode, name, url, parser) VALUES
(1, 1, 4, 'get-all-symbols-in-vn30', 'https://bgapidatafeed.vps.com.vn/getlistckindex/VN30', '["Iter"]'),
(2, 1, 4, 'get-all-symbols-in-vn100', 'https://bgapidatafeed.vps.com.vn/getlistckindex/VN100', '["Iter"]'),
(3, 1, 4, 'get-all-symbols-in-penny', 'https://bgapidatafeed.vps.com.vn/getlistckindex/VNSML', '["Iter"]'),
(4, 1, 4, 'get-all-symbols-in-midcap', 'https://bgapidatafeed.vps.com.vn/getlistckindex/VNMID', '["Iter"]'),
(5, 1, 4, 'get-all-symbols-in-etf', 'https://bgapidatafeed.vps.com.vn/getlistckindex/hsx_e', '["Iter"]'),
(6, 1, 4, 'get-exchange-rate-from-vcb', 'https://www.vietcombank.com.vn/api/exchangerates?date={}', '[{"Match": "Data"}, "Iter", {"Select": ["currencyCode", "sell", "cash"]}]'),
(7, 1, 4, 'get-all-symbols-in-hsx', 'https://api.hsx.vn/l/api/v1/1/securities/stock?pageIndex={}&pageSize={}&alphabet=&sectorId=', '[{"Match": "Code"}, "Iter"]'),
(8, 3, 4, 'get-region-of-specific-ip', 'http://ip-api.com/json/:0', '[{"Match": "regionName"}]')

ON CONFLICT (id) DO NOTHING;

-- ĐỒNG BỘ LẠI SEQUENCE (Cực kỳ quan trọng)
-- Vì chúng ta dùng BIGINT GENERATED BY DEFAULT AS IDENTITY và chèn ID thủ công (1 đến 8),
-- câu lệnh dưới đây sẽ giúp Postgres cập nhật lại con trỏ sequence nội bộ để các bản ghi tự động tăng sau này không bị lỗi trùng khóa (Duplicate Key).
SELECT setval(pg_get_serial_sequence('sys_api_map', 'id'), COALESCE(MAX(id), 1)) FROM sys_api_map;
