from .ajc_com_vn import scrape_ajc
from .ancarat_com import scrape_ancarat
from .doji_vn import scrape_doji
from .hhj_adp_p_com import scrape_hhj_adp_p_com
from .hieuvangthanhtau_com_vn import scrape_hieuvangthanhtau
from .hoakimnguyen_com import scrape_hoakimnguyen
from .hongphucapp_halozend_com import scrape_hongphucapp_halozend
from .huythanhjewelry_com import scrape_huythanhjewelry
from .kimchau_info import scrape_kimchau_info
from .kimkhanhviethung_vn import scrape_kimkhanhviethung
from .kimlongdongthap_vn import scrape_kimlong_dt
from .kimnganphuc_vn import scrape_kimnganphuc
from .kimphat_com_vn import scrape_kimphat
from .kimtaingocdiamond_com import scrape_kimtaingoc
from .kimthanhh_com import scrape_kimthanhh
from .kimtincantho_com import scrape_kimtin_cantho
from .mihong_vn import scrape_mihong
from .minhvujewelry_vn import scrape_minhvu
from .ngocbinh_com_vn import scrape_ngocbinh
from .ngocthinh_jewelry_vn import scrape_ngocthinh
from .phuquy_com_vn import scrape_phuquy
from .sjc_com_vn import scrape_sjc
from .tiemvanghoangchieu_com import scrape_hoang_chieu
from .tiemvanghongnga_com import scrape_hong_nga
from .tiemvangngocthuy_com import scrape_ngoc_thuy
from .tiemvangtrongnghia_com import scrape_kim_trong_nghia
from .tiemvangvanthong_com import scrape_van_thong
from .tiemvangxuantung_com import scrape_xuan_tung
