//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wms_lots")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tenant_id: i32,
    pub stock_id: i32,
    pub lot_number: String,
    pub quantity: i32,
    pub supplier: Option<String>,
    pub entry_date: DateTimeUtc,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub cost_price: Option<Decimal>,
    pub status: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
