//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14
mod broker_limitation;
mod brokers;
mod mapping_broker_resolution;
mod mapping_product_in_store_to_symbol;
mod price_current;
mod price_history;
mod products;
mod resolutions;
mod store_locations;
mod stores;
mod symbols;
use broker_limitation::Entity as BrokerLimitation;
use brokers::Entity as Brokers;
use mapping_broker_resolution::Entity as MappingBrokerResolution;
use mapping_product_in_store_to_symbol::Entity as MappingProductInStoreToSymbol;
use price_current::Entity as PriceCurrent;
use price_history::Entity as PriceHistory;
use products::Entity as Products;
use resolutions::Entity as Resolutions;
use store_locations::Entity as StoreLocations;
use stores::Entity as Stores;
use symbols::Entity as Symbols;

use std::collections::BTreeMap;
use std::sync::Arc;

use chrono::Utc;
use serde::{Deserialize, Serialize};
use utoipa::{IntoParams, ToSchema};

use crate::resolver::Resolver;
use sea_orm::entity::prelude::Expr;
use sea_orm::sea_query::OnConflict;
use sea_orm::{
    ActiveModelTrait, ColumnTrait, Condition, DatabaseConnection, DbErr, EntityTrait, JoinType,
    QueryFilter, QueryOrder, QuerySelect, RuntimeErr, Set, TransactionTrait,
};
use sea_query::Alias;

pub struct Investing {
    resolver: Arc<Resolver>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, ToSchema, IntoParams)]
pub struct Location {
    pub district: Option<String>,
    pub province: Option<String>,
    pub latitude: Option<f32>,
    pub longtitude: Option<f32>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, ToSchema, IntoParams)]
pub struct Store {
    pub id: Option<i32>,
    pub name: Option<String>,
    pub locations: Option<Vec<Location>>,
    pub products: Option<ListProduct>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, ToSchema, IntoParams)]
pub struct ListProduct {
    data: Vec<Product>,

    #[serde(skip_serializing_if = "Option::is_none")]
    next_after: Option<i32>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, ToSchema, IntoParams)]
pub struct Product {
    pub id: Option<i32>,
    pub name: Option<String>,
    pub symbol: Option<String>,
}

impl Investing {
    pub fn new(resolver: &Arc<Resolver>) -> Self {
        Self {
            resolver: resolver.clone(),
        }
    }

    fn dbt(&self, tenant_id: i64) -> &DatabaseConnection {
        self.resolver.database(tenant_id)
    }

    pub async fn convert_to_real_broker(
        &self,
        tenant_id: i64,
        broker: String,
    ) -> Result<String, DbErr> {
        let alias_table = Alias::new("real_broker");

        match Brokers::find()
            .join_as(
                JoinType::LeftJoin,
                brokers::Entity::belongs_to(Brokers)
                    .from(brokers::Column::Alias)
                    .to(brokers::Column::Id)
                    .into(),
                alias_table.clone(),
            )
            .select_only()
            .column_as(brokers::Column::Name, "original")
            .column_as(Expr::col((alias_table, brokers::Column::Name)), "real")
            .filter(brokers::Column::Name.eq(broker.clone()))
            .into_tuple::<(String, Option<String>)>()
            .one(self.dbt(tenant_id))
            .await?
        {
            Some((_, Some(real))) => Ok(real),
            Some((original, None)) => Ok(original),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found broker {broker}",
            )))),
        }
    }

    pub async fn convert_to_broker_resolution(
        &self,
        tenant_id: i64,
        broker: &String,
        resolution: &String,
    ) -> Result<String, DbErr> {
        // Query DB nếu chưa có cache
        let res: Option<String> = MappingBrokerResolution::find()
            .join_rev(
                JoinType::InnerJoin,
                brokers::Entity::belongs_to(MappingBrokerResolution)
                    .from(brokers::Column::Id)
                    .to(mapping_broker_resolution::Column::BrokerId)
                    .into(),
            )
            .join_rev(
                JoinType::InnerJoin,
                resolutions::Entity::belongs_to(MappingBrokerResolution)
                    .from(resolutions::Column::Id)
                    .to(mapping_broker_resolution::Column::ResolutionId)
                    .into(),
            )
            .filter(brokers::Column::Name.eq(broker))
            .filter(resolutions::Column::Resolution.eq(resolution))
            .select_only()
            .column(mapping_broker_resolution::Column::Resolution)
            .into_tuple::<String>()
            .one(self.dbt(tenant_id))
            .await?;

        match res {
            Some(res) => Ok(res),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Resolution {} is not supported for {}",
                resolution, broker
            )))),
        }
    }

    pub async fn list_resolutions(&self, tenant_id: i64) -> Result<Vec<String>, DbErr> {
        // Query DB
        let res = Resolutions::find()
            .select_only()
            .column(resolutions::Column::Resolution)
            .into_tuple::<String>()
            .all(self.dbt(tenant_id))
            .await?;

        Ok(res)
    }

    pub async fn list_brokers(
        &self,
        tenant_id: i64,
        after: i32,
        limit: u64,
        user_id: &Option<String>,
    ) -> Result<(Vec<String>, i32), DbErr> {
        // cache broker theo id → name

        let mut query = Brokers::find()
            .filter(brokers::Column::Id.gt(after))
            .limit(limit);

        if user_id.is_none() {
            query = query
                .join_rev(
                    JoinType::LeftJoin,
                    broker_limitation::Entity::belongs_to(Brokers)
                        .from(broker_limitation::Column::BrokerId)
                        .to(brokers::Column::Id)
                        .into(),
                )
                .filter(
                    Condition::any()
                        .add(broker_limitation::Column::GuestInvisible.is_null())
                        .add(broker_limitation::Column::GuestInvisible.eq(false)),
                );
        }
        let items = query.all(self.dbt(tenant_id)).await?;

        let last_id = items.last().map(|it| it.id).unwrap_or(0);
        let names = items.into_iter().map(|it| it.name).collect();

        Ok((names, last_id))
    }

    pub async fn list_products(
        &self,
        tenant_id: i64,
        broker: &String,
    ) -> Result<Vec<String>, DbErr> {
        let res = Products::find()
            .join_rev(
                JoinType::InnerJoin,
                brokers::Entity::belongs_to(Products)
                    .from(brokers::Column::Id)
                    .to(products::Column::BrokerId)
                    .into(),
            )
            .filter(Condition::all().add(brokers::Column::Name.eq(broker)))
            .select_only()
            .column(products::Column::Name)
            .into_tuple::<String>()
            .all(self.dbt(tenant_id))
            .await?;

        Ok(res)
    }

    pub async fn get_product_id(&self, tenant_id: i64, product: &String) -> Result<i32, DbErr> {
        match Products::find()
            .select_only()
            .column(products::Column::Id)
            .filter(products::Column::Name.eq(product))
            .into_tuple::<i32>()
            .one(self.dbt(tenant_id))
            .await?
        {
            Some(id) => Ok(id),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found product {product}",
            )))),
        }
    }

    pub async fn get_broker_id(&self, tenant_id: i64, broker: &String) -> Result<i32, DbErr> {
        match Brokers::find()
            .select_only()
            .column(brokers::Column::Id)
            .filter(brokers::Column::Name.eq(broker))
            .into_tuple::<i32>()
            .one(self.dbt(tenant_id))
            .await?
        {
            Some(id) => Ok(id),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found broker {broker}",
            )))),
        }
    }

    pub async fn is_broker_enabled(&self, tenant_id: i64, broker: &String) -> Result<bool, DbErr> {
        Ok(Brokers::find()
            .filter(brokers::Column::Name.eq(broker))
            .one(self.dbt(tenant_id))
            .await?
            .is_some())
    }

    pub async fn is_product_enabled(
        &self,
        tenant_id: i64,
        product: &String,
        broker: &String,
    ) -> Result<bool, DbErr> {
        let res = Products::find()
            .join_rev(
                JoinType::InnerJoin,
                brokers::Entity::belongs_to(Products)
                    .from(brokers::Column::Id)
                    .to(products::Column::BrokerId)
                    .into(),
            )
            .filter(
                Condition::all()
                    .add(products::Column::Name.eq(product))
                    .add(brokers::Column::Name.eq(broker))
                    .add(products::Column::Enabled.eq(1)),
            )
            .one(self.dbt(tenant_id))
            .await?;

        let enabled = res.is_some();
        Ok(enabled)
    }

    pub async fn validate_broker_candlesticks_limit(
        &self,
        tenant_id: i64,
        broker: &String,
        user_id: &Option<String>,
        from: i64,
    ) -> Result<(), DbErr> {
        if user_id.is_none()
            && let Some(limit) = BrokerLimitation::find()
                .select_only()
                .column(broker_limitation::Column::GuestMaxHistoryDays)
                .join_rev(
                    JoinType::InnerJoin,
                    brokers::Entity::belongs_to(BrokerLimitation)
                        .from(brokers::Column::Id)
                        .to(broker_limitation::Column::BrokerId)
                        .into(),
                )
                .filter(brokers::Column::Name.eq(broker))
                .into_tuple::<i32>()
                .one(self.dbt(tenant_id))
                .await?
            && from < Utc::now().timestamp() - limit as i64 * 24 * 60 * 60
        {
            Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Broker {broker} is limited to access data",
            ))))
        } else {
            Ok(())
        }
    }

    pub async fn validate_symbol_listing_limit(
        &self,
        tenant_id: i64,
        symbol: &String,
        user_id: &Option<String>,
    ) -> Result<(), DbErr> {
        if user_id.is_none()
            && let Some(limit) = BrokerLimitation::find()
                .select_only()
                .column(broker_limitation::Column::GuestInvisible)
                .join_rev(
                    JoinType::InnerJoin,
                    symbols::Entity::belongs_to(BrokerLimitation)
                        .from(symbols::Column::BrokerId)
                        .to(broker_limitation::Column::BrokerId)
                        .into(),
                )
                .filter(symbols::Column::Symbol.eq(symbol))
                .into_tuple::<bool>()
                .one(self.dbt(tenant_id))
                .await?
            && limit
        {
            Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Symbol {symbol} is limited to see",
            ))))
        } else {
            Ok(())
        }
    }

    pub async fn validate_broker_listing_limit(
        &self,
        tenant_id: i64,
        broker: &String,
        user_id: &Option<String>,
    ) -> Result<(), DbErr> {
        if user_id.is_none()
            && let Some(limit) = BrokerLimitation::find()
                .select_only()
                .column(broker_limitation::Column::GuestInvisible)
                .join_rev(
                    JoinType::InnerJoin,
                    brokers::Entity::belongs_to(BrokerLimitation)
                        .from(brokers::Column::Id)
                        .to(broker_limitation::Column::BrokerId)
                        .into(),
                )
                .filter(brokers::Column::Name.eq(broker))
                .into_tuple::<bool>()
                .one(self.dbt(tenant_id))
                .await?
            && limit
        {
            Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Broker {broker} is limited to see",
            ))))
        } else {
            Ok(())
        }
    }

    pub async fn update_price(
        &self,
        symbol_id: i32,
        new_buy: f32,
        new_sell: f32,
    ) -> Result<(), DbErr> {
        let price_active = price_current::ActiveModel {
            id: Set(symbol_id),
            buy: Set(new_buy),
            sell: Set(new_sell),
            ..Default::default()
        };

        match PriceCurrent::find_by_id(symbol_id)
            .one(self.dbt(symbol_id.into()))
            .await?
        {
            Some(row) => {
                if row.buy == new_buy && row.sell == new_sell {
                    return Ok(());
                }

                price_active.update(self.dbt(symbol_id.into())).await?;
            }

            None => {
                price_active.insert(self.dbt(symbol_id.into())).await?;
            }
        }

        let history_row = price_history::ActiveModel {
            symbol_id: Set(symbol_id),
            buy: Set(new_buy),
            sell: Set(new_sell),
            ..Default::default()
        };

        history_row.insert(self.dbt(symbol_id.into())).await?;
        Ok(())
    }

    pub async fn get_last_price(&self, symbol_id: i32) -> Result<(f32, f32), DbErr> {
        match PriceCurrent::find_by_id(symbol_id)
            .select_only()
            .column(price_current::Column::Buy)
            .column(price_current::Column::Sell)
            .into_tuple::<(f32, f32)>()
            .one(self.dbt(symbol_id.into()))
            .await?
        {
            Some((buy, sell)) => Ok((buy, sell)),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found symbol {symbol_id}",
            )))),
        }
    }

    pub async fn get_price_history(
        &self,
        symbol_id: i32,
        limit: u64,
    ) -> Result<Vec<(f32, f32)>, DbErr> {
        Ok(PriceHistory::find()
            .select_only()
            .column(price_history::Column::Buy)
            .column(price_history::Column::Sell)
            .filter(price_history::Column::SymbolId.eq(symbol_id))
            .order_by_desc(price_history::Column::CreatedAt) // Lấy giá mới nhất lên đầu
            .limit(limit)
            .into_tuple::<(f32, f32)>()
            .all(self.dbt(symbol_id.into()))
            .await?
            .iter()
            .map(|(buy, sell)| (*buy, *sell))
            .collect::<Vec<_>>())
    }

    pub async fn upsert_symbol(
        &self,
        tenant_id: i64,
        broker_id: i32,
        product_id: i32,
        symbol_code: &String,
    ) -> Result<(), DbErr> {
        Symbols::insert(symbols::ActiveModel {
            broker_id: Set(broker_id),
            product_id: Set(product_id),
            symbol: Set(symbol_code.to_string()),
            updated_at: Set(Some(Utc::now())),
            ..Default::default()
        })
        .on_conflict(
            OnConflict::columns([
                symbols::Column::BrokerId,
                symbols::Column::ProductId,
                symbols::Column::Symbol,
            ])
            .update_column(symbols::Column::UpdatedAt)
            .to_owned(),
        )
        .exec_with_returning(self.dbt(tenant_id))
        .await?;
        Ok(())
    }

    pub async fn get_symbol_id(
        &self,
        tenant_id: i64,
        broker_id: i32,
        symbol: &String,
    ) -> Result<i32, DbErr> {
        match Symbols::find()
            .select_only()
            .column(symbols::Column::Id)
            .filter(symbols::Column::BrokerId.eq(broker_id))
            .filter(symbols::Column::Symbol.eq(symbol.clone()))
            .into_tuple::<i32>()
            .one(self.dbt(tenant_id))
            .await?
        {
            Some(id) => Ok(id),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found symbol {symbol}",
            )))),
        }
    }

    pub async fn list_symbols_by_broker(
        &self,
        tenant_id: i64,
        broker_id: i32,
    ) -> Result<Vec<String>, DbErr> {
        Symbols::find()
            .select_only()
            .column(symbols::Column::Symbol)
            .filter(symbols::Column::BrokerId.eq(broker_id))
            .into_tuple::<String>()
            .all(self.dbt(tenant_id))
            .await
    }

    pub async fn list_symbols_by_product(
        &self,
        tenant_id: i64,
        broker_id: i32,
        product_id: i32,
    ) -> Result<Vec<String>, DbErr> {
        let res = Symbols::find()
            .select_only()
            .column(symbols::Column::Symbol)
            .filter(symbols::Column::BrokerId.eq(broker_id))
            .filter(symbols::Column::ProductId.eq(product_id))
            .into_tuple::<String>()
            .all(self.dbt(tenant_id))
            .await?;

        Ok(res)
    }

    pub async fn store_product_name_to_symbol(
        &self,
        tenant_id: i64,
        store: &String,
        product: &String,
    ) -> Result<String, DbErr> {
        match MappingProductInStoreToSymbol::find()
            .select_only()
            .filter(stores::Column::Name.eq(store))
            .filter(mapping_product_in_store_to_symbol::Column::ProductName.eq(product))
            .join_rev(
                JoinType::InnerJoin,
                symbols::Entity::belongs_to(MappingProductInStoreToSymbol)
                    .from(symbols::Column::Id)
                    .to(mapping_product_in_store_to_symbol::Column::Id)
                    .into(),
            )
            .join_rev(
                JoinType::InnerJoin,
                store_locations::Entity::belongs_to(MappingProductInStoreToSymbol)
                    .from(store_locations::Column::Id)
                    .to(mapping_product_in_store_to_symbol::Column::Store)
                    .into(),
            )
            .column(symbols::Column::Symbol)
            .into_tuple::<String>()
            .one(self.dbt(tenant_id))
            .await?
        {
            Some(symbol) => Ok(symbol),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found {product} of store {store}",
            )))),
        }
    }

    pub async fn list_paginated_stores(
        &self,
        tenant_id: i64,
        after: i32,
        limit: u64,
    ) -> Result<Vec<Store>, DbErr> {
        let rows = StoreLocations::find()
            .select_only()
            .column(stores::Column::Id)
            .column(stores::Column::Name)
            .column(store_locations::Column::District)
            .column(store_locations::Column::Province)
            .column(store_locations::Column::Latitude)
            .column(store_locations::Column::Longtitude)
            .join_rev(
                JoinType::InnerJoin,
                Stores::belongs_to(StoreLocations)
                    .from(stores::Column::Id)
                    .to(store_locations::Column::Store)
                    .into(),
            )
            .filter(store_locations::Column::Id.gt(after))
            .limit(limit)
            .into_tuple::<(i32, String, String, String, f32, f32)>()
            .all(self.dbt(tenant_id))
            .await?;

        let mut store_map = BTreeMap::new();

        for (id, name, district, province, lat, long) in rows {
            let entry = store_map.entry(id).or_insert(Store {
                id: Some(id),
                name: Some(name),
                locations: Some(Vec::new()),
                products: None,
            });

            if let Some(ref mut locs) = entry.locations {
                locs.push(Location {
                    district: Some(district),
                    province: Some(province),
                    latitude: Some(lat),
                    longtitude: Some(long),
                });
            }
        }

        // 3. Chuyển Map thành Vec kết quả
        Ok(store_map.into_values().collect())
    }

    pub async fn create_products(
        &self,
        tenant_id: i64,
        broker_id: i32,
        store: &String,
        products: Vec<Product>,
    ) -> Result<ListProduct, DbErr> {
        let mut active_models = Vec::new();
        let mut ret = Vec::new();
        let store = self.get_store_detail(tenant_id, store, 0, 0, false).await?;

        for product in products {
            let symbol = product.symbol.ok_or_else(|| {
                DbErr::Query(RuntimeErr::Internal("`id` mustn't be None".to_string()))
            })?;
            let id = self.get_symbol_id(tenant_id, broker_id, &symbol).await?;
            let product_name = product.name.ok_or_else(|| {
                DbErr::Query(RuntimeErr::Internal("`name` mustn't be None".to_string()))
            })?;
            let store_id = store.id.ok_or_else(|| {
                DbErr::Query(RuntimeErr::Internal(
                    "`store.id` mustn't be None".to_string(),
                ))
            })?;

            active_models.push(mapping_product_in_store_to_symbol::ActiveModel {
                id: Set(id),
                store: Set(store_id),
                product_name: Set(product_name.clone()),
                ..Default::default()
            });

            ret.push(Product {
                id: Some(id),
                name: Some(product_name.clone()),
                symbol: Some(symbol),
            });
        }

        mapping_product_in_store_to_symbol::Entity::insert_many(active_models)
            .exec_with_returning(self.dbt(tenant_id))
            .await?;
        Ok(ListProduct {
            data: ret,
            next_after: None,
        })
    }

    pub async fn get_store_detail(
        &self,
        tenant_id: i64,
        name: &String,
        after: i32,
        limit: u64,
        detail: bool,
    ) -> Result<Store, DbErr> {
        let rows = StoreLocations::find()
            .select_only()
            .column(stores::Column::Id)
            .column(stores::Column::Name)
            .column(store_locations::Column::District)
            .column(store_locations::Column::Province)
            .column(store_locations::Column::Latitude)
            .column(store_locations::Column::Longtitude)
            .join_rev(
                JoinType::InnerJoin,
                stores::Entity::belongs_to(StoreLocations)
                    .from(stores::Column::Id)
                    .to(store_locations::Column::Store)
                    .into(),
            )
            .filter(stores::Column::Name.eq(name))
            .into_tuple::<(i32, String, String, String, f32, f32)>()
            .all(self.dbt(tenant_id))
            .await?;

        if rows.is_empty() {
            return Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found store {name}",
            ))));
        }

        let (store_id, store_name, _, _, _, _) = rows.first().ok_or_else(|| {
            DbErr::Query(RuntimeErr::Internal(format!("Not found store `{name}`")))
        })?;

        let locations: Vec<Location> = rows
            .iter()
            .map(|(_, _, district, province, lat, long)| Location {
                district: Some(district.clone()),
                province: Some(province.clone()),
                latitude: Some(*lat),
                longtitude: Some(*long),
            })
            .collect();

        let products_list = if detail {
            let data = mapping_product_in_store_to_symbol::Entity::find()
                .select_only()
                .column(mapping_product_in_store_to_symbol::Column::Id)
                .column(mapping_product_in_store_to_symbol::Column::ProductName)
                .filter(mapping_product_in_store_to_symbol::Column::Store.eq(*store_id))
                .filter(mapping_product_in_store_to_symbol::Column::Id.gt(after))
                .limit(limit)
                .into_tuple::<(i32, String)>()
                .all(self.dbt(tenant_id))
                .await?
                .into_iter()
                .map(|(id, product_name)| Product {
                    id: Some(id),
                    name: Some(product_name),
                    ..Default::default()
                })
                .collect::<Vec<Product>>();

            let next_after = if data.len() as u64 == limit {
                data.last().and_then(|p| p.id)
            } else {
                None
            };

            Some(ListProduct { data, next_after })
        } else {
            None
        };

        Ok(Store {
            id: Some(*store_id),
            name: Some(store_name.clone()),
            locations: Some(locations),
            products: products_list,
        })
    }

    pub async fn create_stores(
        &self,
        tenant_id: i64,
        stores: Vec<Store>,
    ) -> Result<Vec<Store>, DbErr> {
        let db = self.dbt(tenant_id);

        db.transaction::<_, Vec<Store>, DbErr>(|txn| {
            Box::pin(async move {
                let mut created_stores = Vec::new();

                for store in stores {
                    let store_name = store
                        .name
                        .ok_or_else(|| DbErr::Custom("`name` mustn't be None".to_string()))?;

                    let inserted_store = stores::Entity::insert(stores::ActiveModel {
                        name: Set(store_name),
                        ..Default::default()
                    })
                    .exec_with_returning(txn)
                    .await?;

                    let mut current_locations = Vec::new();
                    if let Some(locations) = store.locations {
                        let location_models: Vec<store_locations::ActiveModel> = locations
                            .into_iter()
                            .map(|loc| store_locations::ActiveModel {
                                store: Set(inserted_store.id),
                                district: Set(loc.district.unwrap_or_default()),
                                province: Set(loc.province.unwrap_or_default()),
                                latitude: Set(loc.latitude.unwrap_or_default()),
                                longtitude: Set(loc.longtitude.unwrap_or_default()),
                                ..Default::default()
                            })
                            .collect();

                        if !location_models.is_empty() {
                            let inserted_locs =
                                store_locations::Entity::insert_many(location_models)
                                    .exec_with_returning(txn)
                                    .await?;

                            for l in inserted_locs {
                                current_locations.push(Location {
                                    district: Some(l.district),
                                    province: Some(l.province),
                                    latitude: Some(l.latitude),
                                    longtitude: Some(l.longtitude),
                                });
                            }
                        }
                    }

                    created_stores.push(Store {
                        id: Some(inserted_store.id),
                        name: Some(inserted_store.name),
                        locations: if current_locations.is_empty() {
                            None
                        } else {
                            Some(current_locations)
                        },
                        products: None,
                    });
                }
                Ok(created_stores)
            })
        })
        .await
        .map_err(|e| match e {
            sea_orm::TransactionError::Connection(e) => e,
            sea_orm::TransactionError::Transaction(e) => e,
        })
    }
}
