//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14
mod broker_limitation;
mod brokers;
mod mapping_broker_resolution;
mod mapping_product_in_store_to_symbol;
mod price_current;
mod price_history;
mod product_anchors;
mod products;
mod resolutions;
mod store_locations;
mod stores;
mod symbols;
use broker_limitation::Entity as BrokerLimitation;
use brokers::Entity as Brokers;
use mapping_broker_resolution::Entity as MappingBrokerResolution;
use mapping_product_in_store_to_symbol::Entity as MappingProductInStoreToSymbol;
use price_current::Entity as PriceCurrent;
use price_history::Entity as PriceHistory;
use product_anchors::Entity as ProductAnchors;
use products::Entity as Products;
use resolutions::Entity as Resolutions;
use store_locations::Entity as StoreLocations;
use stores::Entity as Stores;
use symbols::Entity as Symbols;

use std::collections::{BTreeMap, HashMap};
use std::sync::Arc;

use chrono::Utc;
use serde::{Deserialize, Serialize};
use utoipa::{IntoParams, ToSchema};

use crate::resolver::Resolver;
use sea_orm::entity::prelude::Expr;
use sea_orm::sea_query::OnConflict;
use sea_orm::{
    ActiveModelTrait, ColumnTrait, Condition, DatabaseConnection, DbErr, EntityTrait, JoinType,
    QueryFilter, QueryOrder, QuerySelect, RuntimeErr, Set, TransactionTrait,
};
use sea_query::Alias;

pub struct Investing {
    resolver: Arc<Resolver>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, ToSchema, IntoParams)]
pub struct Filter {
    pub from: i64,
    pub to: i64,
    pub interval: u64,
    pub after: i32,
    pub limit: u64,
    pub scope: i32,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, ToSchema, IntoParams)]
pub struct Location {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub district: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub province: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f32>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, ToSchema, IntoParams)]
pub struct Store {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub price: Option<Price>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<Location>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub products: Option<ListProduct>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, ToSchema, IntoParams)]
pub struct ListProduct {
    data: Vec<Product>,

    #[serde(skip_serializing_if = "Option::is_none")]
    next_after: Option<i32>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, ToSchema, IntoParams)]
pub struct Product {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub price: Option<Price>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, ToSchema, IntoParams)]
pub struct Price {
    pub buy: f32,
    pub sell: f32,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<u64>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, ToSchema, IntoParams)]
pub struct Symbol {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub stores: Option<Vec<Store>>,
}

impl Investing {
    pub fn new(resolver: &Arc<Resolver>) -> Self {
        Self {
            resolver: resolver.clone(),
        }
    }

    fn dbt(&self, tenant_id: i64) -> &DatabaseConnection {
        self.resolver.database(tenant_id)
    }

    pub async fn convert_to_real_broker(
        &self,
        tenant_id: i64,
        broker: String,
    ) -> Result<String, DbErr> {
        let alias_table = Alias::new("real_broker");

        match Brokers::find()
            .join_as(
                JoinType::LeftJoin,
                brokers::Entity::belongs_to(Brokers)
                    .from(brokers::Column::Alias)
                    .to(brokers::Column::Id)
                    .into(),
                alias_table.clone(),
            )
            .select_only()
            .column_as(brokers::Column::Name, "original")
            .column_as(Expr::col((alias_table, brokers::Column::Name)), "real")
            .filter(brokers::Column::Name.eq(broker.clone()))
            .into_tuple::<(String, Option<String>)>()
            .one(self.dbt(tenant_id))
            .await?
        {
            Some((_, Some(real))) => Ok(real),
            Some((original, None)) => Ok(original),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found broker {broker}",
            )))),
        }
    }

    pub async fn convert_to_broker_resolution(
        &self,
        tenant_id: i64,
        broker: &String,
        resolution: &String,
    ) -> Result<String, DbErr> {
        // Query DB nếu chưa có cache
        let res: Option<String> = MappingBrokerResolution::find()
            .join_rev(
                JoinType::InnerJoin,
                brokers::Entity::belongs_to(MappingBrokerResolution)
                    .from(brokers::Column::Id)
                    .to(mapping_broker_resolution::Column::BrokerId)
                    .into(),
            )
            .join_rev(
                JoinType::InnerJoin,
                resolutions::Entity::belongs_to(MappingBrokerResolution)
                    .from(resolutions::Column::Id)
                    .to(mapping_broker_resolution::Column::ResolutionId)
                    .into(),
            )
            .filter(brokers::Column::Name.eq(broker))
            .filter(resolutions::Column::Resolution.eq(resolution))
            .select_only()
            .column(mapping_broker_resolution::Column::Resolution)
            .into_tuple::<String>()
            .one(self.dbt(tenant_id))
            .await?;

        match res {
            Some(res) => Ok(res),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Resolution {} is not supported for {}",
                resolution, broker
            )))),
        }
    }

    pub async fn list_resolutions(&self, tenant_id: i64) -> Result<Vec<String>, DbErr> {
        // Query DB
        let res = Resolutions::find()
            .select_only()
            .column(resolutions::Column::Resolution)
            .into_tuple::<String>()
            .all(self.dbt(tenant_id))
            .await?;

        Ok(res)
    }

    pub async fn list_brokers(
        &self,
        tenant_id: i64,
        after: i32,
        limit: u64,
        user_id: &Option<String>,
    ) -> Result<(Vec<String>, i32), DbErr> {
        // cache broker theo id → name

        let mut query = Brokers::find()
            .filter(brokers::Column::Id.gt(after))
            .limit(limit);

        if user_id.is_none() {
            query = query
                .join_rev(
                    JoinType::LeftJoin,
                    broker_limitation::Entity::belongs_to(Brokers)
                        .from(broker_limitation::Column::BrokerId)
                        .to(brokers::Column::Id)
                        .into(),
                )
                .filter(
                    Condition::any()
                        .add(broker_limitation::Column::GuestInvisible.is_null())
                        .add(broker_limitation::Column::GuestInvisible.eq(false)),
                );
        }
        let items = query.all(self.dbt(tenant_id)).await?;

        let last_id = items.last().map(|it| it.id).unwrap_or(0);
        let names = items.into_iter().map(|it| it.name).collect();

        Ok((names, last_id))
    }

    pub async fn list_products(
        &self,
        tenant_id: i64,
        broker: &String,
    ) -> Result<Vec<String>, DbErr> {
        let res = Products::find()
            .join_rev(
                JoinType::InnerJoin,
                brokers::Entity::belongs_to(Products)
                    .from(brokers::Column::Id)
                    .to(products::Column::BrokerId)
                    .into(),
            )
            .filter(Condition::all().add(brokers::Column::Name.eq(broker)))
            .select_only()
            .column(products::Column::Name)
            .into_tuple::<String>()
            .all(self.dbt(tenant_id))
            .await?;

        Ok(res)
    }

    pub async fn get_product_id(&self, tenant_id: i64, product: &String) -> Result<i32, DbErr> {
        match Products::find()
            .select_only()
            .column(products::Column::Id)
            .filter(products::Column::Name.eq(product))
            .into_tuple::<i32>()
            .one(self.dbt(tenant_id))
            .await?
        {
            Some(id) => Ok(id),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found product {product}",
            )))),
        }
    }

    pub async fn get_broker_id(&self, tenant_id: i64, broker: &String) -> Result<i32, DbErr> {
        match Brokers::find()
            .select_only()
            .column(brokers::Column::Id)
            .filter(brokers::Column::Name.eq(broker))
            .into_tuple::<i32>()
            .one(self.dbt(tenant_id))
            .await?
        {
            Some(id) => Ok(id),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found broker {broker}",
            )))),
        }
    }

    pub async fn is_broker_enabled(&self, tenant_id: i64, broker: &String) -> Result<bool, DbErr> {
        Ok(Brokers::find()
            .filter(brokers::Column::Name.eq(broker))
            .one(self.dbt(tenant_id))
            .await?
            .is_some())
    }

    pub async fn is_product_enabled(
        &self,
        tenant_id: i64,
        product: &String,
        broker: &String,
    ) -> Result<bool, DbErr> {
        let res = Products::find()
            .join_rev(
                JoinType::InnerJoin,
                brokers::Entity::belongs_to(Products)
                    .from(brokers::Column::Id)
                    .to(products::Column::BrokerId)
                    .into(),
            )
            .filter(
                Condition::all()
                    .add(products::Column::Name.eq(product))
                    .add(brokers::Column::Name.eq(broker))
                    .add(products::Column::Enabled.eq(1)),
            )
            .one(self.dbt(tenant_id))
            .await?;

        let enabled = res.is_some();
        Ok(enabled)
    }

    pub async fn is_product_storing_data(
        &self,
        tenant_id: i64,
        product: &String,
        broker: &String,
    ) -> Result<bool, DbErr> {
        let res = Products::find()
            .join_rev(
                JoinType::InnerJoin,
                brokers::Entity::belongs_to(Products)
                    .from(brokers::Column::Id)
                    .to(products::Column::BrokerId)
                    .into(),
            )
            .filter(
                Condition::all()
                    .add(products::Column::Name.eq(product))
                    .add(brokers::Column::Name.eq(broker))
                    .add(products::Column::Stored.eq(1)),
            )
            .one(self.dbt(tenant_id))
            .await?;

        let enabled = res.is_some();
        Ok(enabled)
    }

    pub async fn validate_broker_candlesticks_limit(
        &self,
        tenant_id: i64,
        broker: &String,
        user_id: &Option<String>,
        from: i64,
    ) -> Result<(), DbErr> {
        if user_id.is_none()
            && let Some(limit) = BrokerLimitation::find()
                .select_only()
                .column(broker_limitation::Column::GuestMaxHistoryDays)
                .join_rev(
                    JoinType::InnerJoin,
                    brokers::Entity::belongs_to(BrokerLimitation)
                        .from(brokers::Column::Id)
                        .to(broker_limitation::Column::BrokerId)
                        .into(),
                )
                .filter(brokers::Column::Name.eq(broker))
                .into_tuple::<i32>()
                .one(self.dbt(tenant_id))
                .await?
            && from < Utc::now().timestamp() - limit as i64 * 24 * 60 * 60
        {
            Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Broker {broker} is limited to access data",
            ))))
        } else {
            Ok(())
        }
    }

    pub async fn validate_symbol_listing_limit(
        &self,
        tenant_id: i64,
        symbol: &String,
        user_id: &Option<String>,
    ) -> Result<(), DbErr> {
        if user_id.is_none()
            && let Some(limit) = BrokerLimitation::find()
                .select_only()
                .column(broker_limitation::Column::GuestInvisible)
                .join_rev(
                    JoinType::InnerJoin,
                    symbols::Entity::belongs_to(BrokerLimitation)
                        .from(symbols::Column::BrokerId)
                        .to(broker_limitation::Column::BrokerId)
                        .into(),
                )
                .filter(symbols::Column::Symbol.eq(symbol))
                .into_tuple::<bool>()
                .one(self.dbt(tenant_id))
                .await?
            && limit
        {
            Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Symbol {symbol} is limited to see",
            ))))
        } else {
            Ok(())
        }
    }

    pub async fn validate_broker_listing_limit(
        &self,
        tenant_id: i64,
        broker: &String,
        user_id: &Option<String>,
    ) -> Result<(), DbErr> {
        if user_id.is_none()
            && let Some(limit) = BrokerLimitation::find()
                .select_only()
                .column(broker_limitation::Column::GuestInvisible)
                .join_rev(
                    JoinType::InnerJoin,
                    brokers::Entity::belongs_to(BrokerLimitation)
                        .from(brokers::Column::Id)
                        .to(broker_limitation::Column::BrokerId)
                        .into(),
                )
                .filter(brokers::Column::Name.eq(broker))
                .into_tuple::<bool>()
                .one(self.dbt(tenant_id))
                .await?
            && limit
        {
            Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Broker {broker} is limited to see",
            ))))
        } else {
            Ok(())
        }
    }

    pub async fn list_history_price_of_symbols(
        &self,
        tenant_id: i64,
        broker: &str,
        filter: Filter,
    ) -> Result<HashMap<i32, HashMap<i32, Vec<Price>>>, DbErr> {
        let symbol_ids = symbols::Entity::find()
            .select_only()
            .column(symbols::Column::Id)
            .join_rev(
                JoinType::InnerJoin,
                product_anchors::Entity::belongs_to(symbols::Entity)
                    .from(product_anchors::Column::Symbol)
                    .to(symbols::Column::Id)
                    .into(),
            )
            .join_rev(
                JoinType::InnerJoin,
                brokers::Entity::belongs_to(symbols::Entity)
                    .from(brokers::Column::Id)
                    .to(symbols::Column::BrokerId)
                    .into(),
            )
            .filter(product_anchors::Column::Scope.eq(filter.scope))
            .filter(brokers::Column::Name.eq(broker))
            .filter(symbols::Column::Id.gt(filter.after))
            .order_by_asc(symbols::Column::Id)
            .limit(filter.limit)
            .into_tuple::<i32>()
            .all(self.dbt(tenant_id))
            .await?;

        if symbol_ids.is_empty() {
            return Ok(HashMap::new());
        }

        let raw_history = price_history::Entity::find()
            .select_only()
            .column(symbols::Column::Id)
            .column(mapping_product_in_store_to_symbol::Column::Id)
            .column(price_history::Column::Buy)
            .column(price_history::Column::Sell)
            .column(price_history::Column::UpdatedAt)
            .join_rev(
                JoinType::InnerJoin,
                mapping_product_in_store_to_symbol::Entity::belongs_to(price_history::Entity)
                    .from(mapping_product_in_store_to_symbol::Column::Id)
                    .to(price_history::Column::SymbolId)
                    .into(),
            )
            .join_rev(
                JoinType::InnerJoin,
                product_anchors::Entity::belongs_to(mapping_product_in_store_to_symbol::Entity)
                    .from(product_anchors::Column::Id)
                    .to(mapping_product_in_store_to_symbol::Column::Id)
                    .into(),
            )
            .join_rev(
                JoinType::InnerJoin,
                symbols::Entity::belongs_to(product_anchors::Entity)
                    .from(symbols::Column::Id)
                    .to(product_anchors::Column::Symbol)
                    .into(),
            )
            .filter(symbols::Column::Id.is_in(symbol_ids))
            .filter(product_anchors::Column::Scope.eq(filter.scope))
            .filter(price_history::Column::UpdatedAt.between(
                chrono::DateTime::from_timestamp(filter.from, 0).unwrap_or_default(),
                chrono::DateTime::from_timestamp(filter.to, 0).unwrap_or_default(),
            ))
            .order_by_asc(symbols::Column::Id)
            .order_by_asc(mapping_product_in_store_to_symbol::Column::Id) // Quan trọng để grouping
            .order_by_asc(price_history::Column::CreatedAt)
            .into_tuple::<(i32, i32, f32, f32, chrono::DateTime<chrono::Utc>)>()
            .all(self.dbt(tenant_id))
            .await?;

        let mut result_map = HashMap::<i32, HashMap<i32, Vec<Price>>>::new();
        let mut last_buckets = HashMap::<(i32, i32), i64>::new();

        for (symbol_id, product_id, buy, sell, created_at) in raw_history {
            let ts = created_at.timestamp();
            let bucket = ts / (filter.interval as i64);
            let pair_key = (symbol_id, product_id);

            if last_buckets.get(&pair_key) != Some(&bucket) {
                result_map
                    .entry(symbol_id)
                    .or_default()
                    .entry(product_id)
                    .or_default()
                    .push(Price {
                        buy,
                        sell,
                        ..Default::default()
                    });

                last_buckets.insert(pair_key, bucket);
            }
        }

        Ok(result_map)
    }

    pub async fn list_current_price_of_symbols(
        &self,
        tenant_id: i64,
        broker: &str,
        filter: Filter,
    ) -> Result<HashMap<i32, HashMap<i32, Price>>, DbErr> {
        let symbol_ids = Symbols::find()
            .select_only()
            .column(symbols::Column::Id)
            .join_rev(
                JoinType::InnerJoin,
                Brokers::belongs_to(Symbols)
                    .from(brokers::Column::Id)
                    .to(symbols::Column::BrokerId)
                    .into(),
            )
            .filter(brokers::Column::Name.eq(broker))
            .filter(symbols::Column::Id.gt(filter.after))
            .order_by_asc(symbols::Column::Id)
            .limit(filter.limit)
            .into_tuple::<i32>()
            .all(self.dbt(tenant_id))
            .await?;

        if symbol_ids.is_empty() {
            return Ok(HashMap::new());
        }

        let raw_data = Symbols::find()
            .select_only()
            .column(symbols::Column::Id)
            .column(mapping_product_in_store_to_symbol::Column::Id)
            .column(price_current::Column::Buy)
            .column(price_current::Column::Sell)
            .join_rev(
                JoinType::InnerJoin,
                ProductAnchors::belongs_to(Symbols)
                    .from(product_anchors::Column::Symbol)
                    .to(symbols::Column::Id)
                    .into(),
            )
            .join_rev(
                JoinType::InnerJoin,
                MappingProductInStoreToSymbol::belongs_to(ProductAnchors)
                    .from(mapping_product_in_store_to_symbol::Column::Id)
                    .to(product_anchors::Column::Id)
                    .into(),
            )
            .join_rev(
                JoinType::InnerJoin,
                PriceCurrent::belongs_to(MappingProductInStoreToSymbol)
                    .from(price_current::Column::Id)
                    .to(mapping_product_in_store_to_symbol::Column::Id)
                    .into(),
            )
            .filter(symbols::Column::Id.is_in(symbol_ids))
            .filter(product_anchors::Column::Scope.eq(filter.scope))
            .into_tuple::<(i32, i32, Option<f32>, Option<f32>)>()
            .all(self.dbt(tenant_id))
            .await?;

        let mut result_map = HashMap::<i32, HashMap<i32, Price>>::new();

        for (s_id, p_id, buy, sell) in raw_data {
            let price = Price {
                buy: buy.unwrap_or(0.0),
                sell: sell.unwrap_or(0.0),
                ..Default::default()
            };

            result_map.entry(s_id).or_default().insert(p_id, price);
        }

        Ok(result_map)
    }

    pub async fn list_current_price_of_store(
        &self,
        tenant_id: i64,
        store_id: i32,
    ) -> Result<HashMap<String, Price>, DbErr> {
        Ok(PriceCurrent::find()
            .select_only()
            .column(mapping_product_in_store_to_symbol::Column::ProductName)
            .column(price_current::Column::Buy)
            .column(price_current::Column::Sell)
            .join_rev(
                JoinType::InnerJoin,
                MappingProductInStoreToSymbol::belongs_to(PriceCurrent)
                    .from(mapping_product_in_store_to_symbol::Column::Id)
                    .to(price_current::Column::Id)
                    .into(),
            )
            .filter(mapping_product_in_store_to_symbol::Column::Store.eq(store_id))
            .into_tuple::<(String, f32, f32)>()
            .all(self.dbt(tenant_id))
            .await?
            .into_iter()
            .map(|(product_name, buy_price, sell_price)| {
                (
                    product_name,
                    Price {
                        buy: buy_price,
                        sell: sell_price,
                        ..Default::default()
                    },
                )
            })
            .collect::<HashMap<_, _>>())
    }

    pub async fn get_price(
        &self,
        tenant_id: i64,
        symbol_ids: &[i32],
    ) -> Result<HashMap<i32, Price>, DbErr> {
        let results = PriceCurrent::find()
            .select_only()
            .column(price_current::Column::Id)
            .column(price_current::Column::Buy)
            .column(price_current::Column::Sell)
            .filter(price_current::Column::Id.is_in(symbol_ids.to_vec()))
            .into_tuple::<(i32, f32, f32)>()
            .all(self.dbt(tenant_id)) // Trả về Vec<(i32, f32, f32)>
            .await?;

        let price_map: HashMap<i32, Price> = results
            .into_iter()
            .map(|(id, buy, sell)| {
                (
                    id,
                    Price {
                        buy,
                        sell,
                        ..Default::default()
                    },
                )
            })
            .collect();

        if price_map.is_empty() && !symbol_ids.is_empty() {
            return Err(DbErr::Custom("No products found".to_string()));
        }

        Ok(price_map)
    }

    pub async fn update_price(&self, symbol_id: i32, price: Price) -> Result<(), DbErr> {
        let price_active = price_current::ActiveModel {
            id: Set(symbol_id),
            buy: Set(price.buy),
            sell: Set(price.sell),
            ..Default::default()
        };

        match PriceCurrent::find_by_id(symbol_id)
            .one(self.dbt(symbol_id.into()))
            .await?
        {
            Some(row) => {
                if row.buy != price.buy || row.sell != price.sell {
                    price_active.update(self.dbt(symbol_id.into())).await?;
                }
            }

            None => {
                price_active.insert(self.dbt(symbol_id.into())).await?;
            }
        }

        let history_row = price_history::ActiveModel {
            symbol_id: Set(symbol_id),
            buy: Set(price.buy),
            sell: Set(price.sell),
            ..Default::default()
        };

        history_row.insert(self.dbt(symbol_id.into())).await?;
        Ok(())
    }

    pub async fn get_price_history(
        &self,
        symbol_id: i32,
        limit: u64,
    ) -> Result<Vec<(f32, f32)>, DbErr> {
        Ok(PriceHistory::find()
            .select_only()
            .column(price_history::Column::Buy)
            .column(price_history::Column::Sell)
            .filter(price_history::Column::SymbolId.eq(symbol_id))
            .order_by_desc(price_history::Column::CreatedAt) // Lấy giá mới nhất lên đầu
            .limit(limit)
            .into_tuple::<(f32, f32)>()
            .all(self.dbt(symbol_id.into()))
            .await?
            .iter()
            .map(|(buy, sell)| (*buy, *sell))
            .collect::<Vec<_>>())
    }

    pub async fn upsert_symbol(
        &self,
        tenant_id: i64,
        broker_id: i32,
        product_id: i32,
        symbol_code: &String,
    ) -> Result<(), DbErr> {
        Symbols::insert(symbols::ActiveModel {
            broker_id: Set(broker_id),
            product_id: Set(product_id),
            symbol: Set(symbol_code.to_string()),
            updated_at: Set(Some(Utc::now())),
            ..Default::default()
        })
        .on_conflict(
            OnConflict::columns([
                symbols::Column::BrokerId,
                symbols::Column::ProductId,
                symbols::Column::Symbol,
            ])
            .update_column(symbols::Column::UpdatedAt)
            .to_owned(),
        )
        .exec_with_returning(self.dbt(tenant_id))
        .await?;
        Ok(())
    }

    pub async fn get_symbol_id(
        &self,
        tenant_id: i64,
        broker_id: i32,
        product_id: Option<i32>,
        symbol: &String,
    ) -> Result<i32, DbErr> {
        let mut query = Symbols::find()
            .select_only()
            .column(symbols::Column::Id)
            .filter(symbols::Column::BrokerId.eq(broker_id))
            .filter(symbols::Column::Symbol.eq(symbol.clone()));

        if let Some(product_id) = product_id {
            query = query.filter(symbols::Column::ProductId.eq(product_id));
        }

        match query.into_tuple::<i32>().one(self.dbt(tenant_id)).await? {
            Some(id) => Ok(id),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found symbol {symbol}",
            )))),
        }
    }

    pub async fn list_symbols_by_broker(
        &self,
        tenant_id: i64,
        broker_id: i32,
    ) -> Result<Vec<String>, DbErr> {
        Symbols::find()
            .select_only()
            .column(symbols::Column::Symbol)
            .filter(symbols::Column::BrokerId.eq(broker_id))
            .into_tuple::<String>()
            .all(self.dbt(tenant_id))
            .await
    }

    pub async fn list_symbols_by_product(
        &self,
        tenant_id: i64,
        broker_id: i32,
        product_id: i32,
    ) -> Result<Vec<String>, DbErr> {
        let res = Symbols::find()
            .select_only()
            .column(symbols::Column::Symbol)
            .filter(symbols::Column::BrokerId.eq(broker_id))
            .filter(symbols::Column::ProductId.eq(product_id))
            .into_tuple::<String>()
            .all(self.dbt(tenant_id))
            .await?;

        Ok(res)
    }

    pub async fn get_product_id_from_website(
        &self,
        tenant_id: i64,
        store: &String,
        product: &String,
    ) -> Result<i32, DbErr> {
        // @TODO: product has been identified by scope, we will use it to
        //        distribute pricing in map
        match MappingProductInStoreToSymbol::find()
            .select_only()
            .column(mapping_product_in_store_to_symbol::Column::Id)
            .join_rev(
                JoinType::InnerJoin,
                stores::Entity::belongs_to(MappingProductInStoreToSymbol)
                    .from(stores::Column::Id)
                    .to(mapping_product_in_store_to_symbol::Column::Store)
                    .into(),
            )
            .filter(mapping_product_in_store_to_symbol::Column::ProductName.eq(product.clone()))
            .filter(stores::Column::Name.eq(store))
            .into_tuple::<i32>()
            .one(self.dbt(tenant_id))
            .await?
        {
            Some(id) => Ok(id),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found {product} in {store}",
            )))),
        }
    }

    pub async fn store_product_name_to_symbol(
        &self,
        tenant_id: i64,
        store: &String,
        product: &String,
    ) -> Result<String, DbErr> {
        match MappingProductInStoreToSymbol::find()
            .select_only()
            .filter(stores::Column::Name.eq(store))
            .filter(mapping_product_in_store_to_symbol::Column::ProductName.eq(product))
            .join_rev(
                JoinType::InnerJoin,
                symbols::Entity::belongs_to(MappingProductInStoreToSymbol)
                    .from(symbols::Column::Id)
                    .to(mapping_product_in_store_to_symbol::Column::Symbol)
                    .into(),
            )
            .join_rev(
                JoinType::InnerJoin,
                stores::Entity::belongs_to(MappingProductInStoreToSymbol)
                    .from(stores::Column::Id)
                    .to(mapping_product_in_store_to_symbol::Column::Store)
                    .into(),
            )
            .column(symbols::Column::Symbol)
            .into_tuple::<String>()
            .one(self.dbt(tenant_id))
            .await?
        {
            Some(symbol) => Ok(symbol),
            None => Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found {product} of store {store}",
            )))),
        }
    }

    pub async fn list_paginated_stores(
        &self,
        tenant_id: i64,
        after: i32,
        limit: u64,
        detail: bool,
    ) -> Result<Vec<Store>, DbErr> {
        if detail {
            let store_ids = Stores::find()
                .select_only()
                .column(stores::Column::Id)
                .filter(stores::Column::Id.gt(after))
                .order_by_asc(stores::Column::Id)
                .limit(limit)
                .into_tuple::<i32>()
                .all(self.dbt(tenant_id))
                .await?;

            if store_ids.is_empty() {
                return Ok(Vec::new());
            }
            let rows = Stores::find()
                .select_only()
                .column(stores::Column::Id)
                .column(stores::Column::Name)
                .column(store_locations::Column::AddressLine)
                .column(store_locations::Column::District)
                .column(store_locations::Column::Province)
                .column(store_locations::Column::Latitude)
                .column(store_locations::Column::Longitude)
                .column(mapping_product_in_store_to_symbol::Column::Id)
                .column(mapping_product_in_store_to_symbol::Column::ProductName)
                .column(symbols::Column::Symbol)
                .column(price_current::Column::Buy)
                .column(price_current::Column::Sell)
                .join_rev(
                    JoinType::LeftJoin,
                    PriceCurrent::belongs_to(MappingProductInStoreToSymbol)
                        .from(price_current::Column::Id)
                        .to(mapping_product_in_store_to_symbol::Column::Id)
                        .into(),
                )
                .join_rev(
                    JoinType::InnerJoin,
                    StoreLocations::belongs_to(Stores)
                        .from(store_locations::Column::Store)
                        .to(stores::Column::Id)
                        .into(),
                )
                .join_rev(
                    JoinType::InnerJoin,
                    MappingProductInStoreToSymbol::belongs_to(Stores)
                        .from(mapping_product_in_store_to_symbol::Column::Store)
                        .to(stores::Column::Id)
                        .into(),
                )
                .join_rev(
                    JoinType::InnerJoin,
                    Symbols::belongs_to(MappingProductInStoreToSymbol)
                        .from(symbols::Column::Id)
                        .to(mapping_product_in_store_to_symbol::Column::Symbol)
                        .into(),
                )
                .filter(stores::Column::Id.is_in(store_ids))
                .order_by_asc(stores::Column::Id)
                .into_tuple::<(
                    i32,
                    String,
                    String,
                    String,
                    String,
                    f32,
                    f32,
                    i32,
                    String,
                    String,
                    Option<f32>,
                    Option<f32>,
                )>()
                .all(self.dbt(tenant_id))
                .await?;

            let mut store_map = BTreeMap::new();
            let mut location_seen = std::collections::HashSet::new();
            let mut product_seen = std::collections::HashSet::new();

            for (
                store_id,
                name,
                address,
                district,
                province,
                latitude,
                longitude,
                product_id,
                product_name,
                symbol,
                buy,
                sell,
            ) in rows
            {
                let entry = store_map.entry(store_id).or_insert(Store {
                    id: Some(store_id),
                    name: Some(name),
                    locations: Some(Vec::new()),
                    products: Some(ListProduct {
                        data: Vec::new(),
                        next_after: None,
                    }),
                    ..Default::default()
                });

                let loc_key = (store_id, district.clone(), province.clone());
                if !location_seen.contains(&loc_key) {
                    if let Some(ref mut locs) = entry.locations {
                        locs.push(Location {
                            address: Some(address),
                            district: Some(district),
                            province: Some(province),
                            latitude: Some(latitude),
                            longitude: Some(longitude),
                        });
                    }
                    location_seen.insert(loc_key);
                }

                let prod_key = (store_id, product_id);
                if !product_seen.contains(&prod_key) {
                    if let Some(ref mut list_prod) = entry.products {
                        list_prod.data.push(Product {
                            id: Some(product_id),
                            name: Some(product_name),
                            symbol: Some(symbol),
                            price: Some(Price {
                                buy: buy.unwrap_or(0.0),
                                sell: sell.unwrap_or(0.0),
                                ..Default::default()
                            }),
                        });
                    }
                    product_seen.insert(prod_key);
                }
            }

            Ok(store_map.into_values().collect())
        } else {
            Ok(Stores::find()
                .select_only()
                .column(stores::Column::Id)
                .column(stores::Column::Name)
                .filter(stores::Column::Id.gt(after))
                .limit(limit)
                .into_tuple::<(i32, String)>()
                .all(self.dbt(tenant_id))
                .await?
                .into_iter()
                .map(|(id, name)| Store {
                    id: Some(id),
                    name: Some(name.to_string()),
                    ..Default::default()
                })
                .collect::<Vec<_>>())
        }
    }

    pub async fn create_products(
        &self,
        tenant_id: i64,
        broker_id: i32,
        store: &String,
        products: Vec<Product>,
    ) -> Result<ListProduct, DbErr> {
        let mut active_models = Vec::new();
        let mut ret = Vec::new();
        let store = self.get_store_detail(tenant_id, store, 0, 0, false).await?;

        for product in products {
            let symbol = product.symbol.ok_or_else(|| {
                DbErr::Query(RuntimeErr::Internal("`id` mustn't be None".to_string()))
            })?;
            let id = self
                .get_symbol_id(tenant_id, broker_id, None, &symbol)
                .await?;
            let product_name = product.name.ok_or_else(|| {
                DbErr::Query(RuntimeErr::Internal("`name` mustn't be None".to_string()))
            })?;
            let store_id = store.id.ok_or_else(|| {
                DbErr::Query(RuntimeErr::Internal(
                    "`store.id` mustn't be None".to_string(),
                ))
            })?;

            active_models.push(mapping_product_in_store_to_symbol::ActiveModel {
                id: Set(id),
                store: Set(store_id),
                product_name: Set(product_name.clone()),
                ..Default::default()
            });

            ret.push(Product {
                id: Some(id),
                name: Some(product_name.clone()),
                symbol: Some(symbol),
                ..Default::default()
            });
        }

        mapping_product_in_store_to_symbol::Entity::insert_many(active_models)
            .exec_with_returning(self.dbt(tenant_id))
            .await?;
        Ok(ListProduct {
            data: ret,
            next_after: None,
        })
    }

    pub async fn get_store_detail(
        &self,
        tenant_id: i64,
        name: &String,
        after: i32,
        limit: u64,
        detail: bool,
    ) -> Result<Store, DbErr> {
        let rows = StoreLocations::find()
            .select_only()
            .column(stores::Column::Id)
            .column(stores::Column::Name)
            .column(store_locations::Column::AddressLine)
            .column(store_locations::Column::District)
            .column(store_locations::Column::Province)
            .column(store_locations::Column::Latitude)
            .column(store_locations::Column::Longitude)
            .join_rev(
                JoinType::InnerJoin,
                stores::Entity::belongs_to(StoreLocations)
                    .from(stores::Column::Id)
                    .to(store_locations::Column::Store)
                    .into(),
            )
            .filter(stores::Column::Name.eq(name))
            .into_tuple::<(i32, String, String, String, String, f32, f32)>()
            .all(self.dbt(tenant_id))
            .await?;

        if rows.is_empty() {
            return Err(DbErr::Query(RuntimeErr::Internal(format!(
                "Not found store {name}",
            ))));
        }

        let (store_id, store_name, _, _, _, _, _) = rows.first().ok_or_else(|| {
            DbErr::Query(RuntimeErr::Internal(format!("Not found store `{name}`")))
        })?;

        let locations: Vec<Location> = rows
            .iter()
            .map(|(_, _, address, district, province, lat, long)| Location {
                address: Some(address.clone()),
                district: Some(district.clone()),
                province: Some(province.clone()),
                latitude: Some(*lat),
                longitude: Some(*long),
            })
            .collect();

        let products_list = if detail {
            let data = mapping_product_in_store_to_symbol::Entity::find()
                .select_only()
                .column(mapping_product_in_store_to_symbol::Column::Id)
                .column(mapping_product_in_store_to_symbol::Column::ProductName)
                .filter(mapping_product_in_store_to_symbol::Column::Store.eq(*store_id))
                .filter(mapping_product_in_store_to_symbol::Column::Id.gt(after))
                .limit(limit)
                .into_tuple::<(i32, String)>()
                .all(self.dbt(tenant_id))
                .await?
                .into_iter()
                .map(|(id, product_name)| Product {
                    id: Some(id),
                    name: Some(product_name),
                    ..Default::default()
                })
                .collect::<Vec<Product>>();

            let next_after = if data.len() as u64 == limit {
                data.last().and_then(|p| p.id)
            } else {
                None
            };

            Some(ListProduct { data, next_after })
        } else {
            None
        };

        Ok(Store {
            id: Some(*store_id),
            name: Some(store_name.clone()),
            locations: Some(locations),
            products: products_list,
            ..Default::default()
        })
    }

    pub async fn create_stores(
        &self,
        tenant_id: i64,
        stores_input: Vec<Store>,
    ) -> Result<Vec<Store>, DbErr> {
        let db = self.dbt(tenant_id);

        db.transaction::<_, Vec<Store>, DbErr>(|txn| {
            Box::pin(async move {
                let store_active_models: Vec<stores::ActiveModel> = stores_input
                    .iter()
                    .map(|s| stores::ActiveModel {
                        name: Set(s.name.clone().unwrap_or_default()),
                        ..Default::default()
                    })
                    .collect();

                if store_active_models.is_empty() {
                    return Ok(Vec::new());
                }

                let inserted_stores = stores::Entity::insert_many(store_active_models)
                    .exec_with_returning(txn)
                    .await?;

                let mut location_active_models = Vec::new();

                for (input_store, inserted_entity) in
                    stores_input.into_iter().zip(inserted_stores.iter())
                {
                    if let Some(locations) = input_store.locations {
                        for loc in locations {
                            location_active_models.push(store_locations::ActiveModel {
                                store: Set(inserted_entity.id),
                                district: Set(loc.district.unwrap_or_default()),
                                province: Set(loc.province.unwrap_or_default()),
                                latitude: Set(loc.latitude.unwrap_or_default()),
                                longitude: Set(loc.longitude.unwrap_or_default()),
                                ..Default::default()
                            });
                        }
                    }
                }

                let mut all_inserted_locations = Vec::new();
                if !location_active_models.is_empty() {
                    all_inserted_locations =
                        store_locations::Entity::insert_many(location_active_models)
                            .exec_with_returning(txn)
                            .await?;
                }

                let mut location_map: HashMap<i32, Vec<Location>> = HashMap::new();
                for l in all_inserted_locations {
                    location_map.entry(l.store).or_default().push(Location {
                        address: Some(l.address_line),
                        district: Some(l.district),
                        province: Some(l.province),
                        latitude: Some(l.latitude),
                        longitude: Some(l.longitude),
                    });
                }

                let result = inserted_stores
                    .into_iter()
                    .map(|s| {
                        let id = s.id;
                        Store {
                            id: Some(id),
                            name: Some(s.name),
                            locations: location_map.remove(&id),
                            ..Default::default()
                        }
                    })
                    .collect();

                Ok(result)
            })
        })
        .await
        .map_err(|e| match e {
            sea_orm::TransactionError::Connection(e) => e,
            sea_orm::TransactionError::Transaction(e) => e,
        })
    }

    pub async fn list_paginated_symbols(
        &self,
        tenant_id: i64,
        broker: &str,
        after: i32,
        limit: u64,
        detail: bool,
    ) -> Result<Vec<Symbol>, DbErr> {
        let symbol_ids = Symbols::find()
            .select_only()
            .column(symbols::Column::Id)
            .filter(symbols::Column::Id.gt(after))
            .order_by_asc(symbols::Column::Id)
            .limit(limit)
            .into_tuple::<i32>()
            .all(self.dbt(tenant_id))
            .await?;

        if symbol_ids.is_empty() {
            return Ok(Vec::new());
        }

        if detail {
            let rows = Symbols::find()
                .select_only()
                .column(symbols::Column::Id)
                .column(symbols::Column::Name)
                .column(symbols::Column::Symbol)
                .column(stores::Column::Id)
                .column(stores::Column::Name)
                .column(price_current::Column::Buy)
                .column(price_current::Column::Sell)
                .join_rev(
                    JoinType::InnerJoin,
                    ProductAnchors::belongs_to(Symbols)
                        .from(product_anchors::Column::Symbol)
                        .to(symbols::Column::Id)
                        .into(),
                )
                .join_rev(
                    JoinType::InnerJoin,
                    MappingProductInStoreToSymbol::belongs_to(ProductAnchors)
                        .from(mapping_product_in_store_to_symbol::Column::Id)
                        .to(product_anchors::Column::Id)
                        .into(),
                )
                .join_rev(
                    JoinType::InnerJoin,
                    Stores::belongs_to(ProductAnchors)
                        .from(stores::Column::Id)
                        .to(product_anchors::Column::Store)
                        .into(),
                )
                .join_rev(
                    JoinType::LeftJoin,
                    PriceCurrent::belongs_to(MappingProductInStoreToSymbol)
                        .from(price_current::Column::Id)
                        .to(mapping_product_in_store_to_symbol::Column::Id)
                        .into(),
                )
                .filter(symbols::Column::Id.is_in(symbol_ids))
                .order_by_asc(symbols::Column::Id)
                .into_tuple::<(i32, String, String, i32, String, Option<f32>, Option<f32>)>()
                .all(self.dbt(tenant_id))
                .await?;

            let mut symbol_map = BTreeMap::new();
            for (sym_id, sym_name, sym_code, store_id, store_name, buy, sell) in rows {
                let symbol_entry = symbol_map.entry(sym_id).or_insert(Symbol {
                    id: Some(sym_id),
                    name: Some(sym_name),
                    symbol: Some(sym_code),
                    stores: Some(Vec::new()),
                });

                if let Some(ref mut stores_list) = symbol_entry.stores {
                    stores_list.push(Store {
                        id: Some(store_id),
                        name: Some(store_name),
                        price: Some(Price {
                            buy: buy.unwrap_or(0.0),
                            sell: sell.unwrap_or(0.0),
                            ..Default::default()
                        }),
                        ..Default::default()
                    });
                }
            }

            Ok(symbol_map.into_values().collect())
        } else {
            Ok(Symbols::find()
                .filter(brokers::Column::Name.eq(broker))
                .filter(symbols::Column::Id.is_in(symbol_ids))
                .join_rev(
                    JoinType::InnerJoin,
                    Brokers::belongs_to(Symbols)
                        .from(brokers::Column::Id)
                        .to(symbols::Column::BrokerId)
                        .into(),
                )
                .order_by_asc(symbols::Column::Id)
                .all(self.dbt(tenant_id))
                .await?
                .into_iter()
                .map(|m| Symbol {
                    id: Some(m.id),
                    name: Some(m.name),
                    symbol: Some(m.symbol),
                    ..Default::default()
                })
                .collect())
        }
    }
}
