location /api/investing/v2/exchange-rate {
    access_by_lua_block {
        local http = require("resty.http")
        local tenant_id = ngx.shared.tenant:get(ngx.var.host)
        if not tenant_id then
            local httpc = http.new()
            local ok, _ = httpc:connect("unix:/var/run/axum")
            if ok then
                local res, _ = httpc:request({
                    path = "/api/admin/v1/seo/tenant/" .. ngx.var.host .. "/id",
                    method = "GET",
                    headers = {
                        ["Host"] = ngx.var.host,
                        ["Connection"] = "Keep-Alive",
                    }
                })
                if res and res.status == 200 then
                    tenant_id = res:read_body()
                    ngx.shared.tenant:set(ngx.var.host, tenant_id, 600)
                end
                httpc:set_keepalive()
            end
        end
        ngx.req.set_header("X-Tenant-Id", tenant_id or "")
    }

    proxy_pass http://backend/api/admin/v1/seo/schemas/6/query;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
