[package]
name = "proxy"
version = "0.1.0"
edition = "2021"
autobins = false

[lib]
name = "proxy"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
backend = { path = "../backend", default-features = false, features = ["proxy"] }
ngx = { version = "0.5.0", features = ["async", "serde", "std"] }
nginx-sys = { version = "0.5.0", features = ["vendored"] }

[features]
default  = ["export-modules"]
export-modules = []

[profile.release]
codegen-units = 1
lto = true
